# Generated by Django 4.2.18 on 2025-03-25 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonModels',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Common.commonmodel')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            bases=('Common.commonmodel',),
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Common.commonmodel')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            bases=('Common.commonmodel',),
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Common.commonmodel')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('sale_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.seasonmodels')),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.typemodel')),
            ],
            bases=('Common.commonmodel',),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Common.commonmodel')),
                ('cost_total', models.FloatField()),
                ('status', models.CharField(max_length=150, unique=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Common.commonmodel',),
        ),
        migrations.CreateModel(
            name='Order_ProductModel',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Common.commonmodel')),
                ('id_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.ordermodel')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.productmodel')),
            ],
            bases=('Common.commonmodel',),
        ),
    ]
